// <auto-generated />
using IntresseKlubbenAPI.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IntresseKlubbenAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ADVLabb4.Models.Interest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Description = "Fiska fiskar i havet.",
                            PersId = 1,
                            Title = "Sportfiske"
                        },
                        new
                        {
                            ID = 2,
                            Description = "Sparka bollar i mål.",
                            PersId = 1,
                            Title = "Fotboll"
                        },
                        new
                        {
                            ID = 3,
                            Description = "Lyfta skrot i gymmet.",
                            PersId = 2,
                            Title = "Styrketräning"
                        },
                        new
                        {
                            ID = 4,
                            Description = "Kolla på katter på youtube",
                            PersId = 3,
                            Title = "Youtube"
                        });
                });

            modelBuilder.Entity("ADVLabb4.Models.Links", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InterestID")
                        .HasColumnType("int");

                    b.Property<int>("PersID")
                        .HasColumnType("int");

                    b.Property<string>("strLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Linkss");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            InterestID = 2,
                            PersID = 1,
                            strLink = "www.nånting.com"
                        },
                        new
                        {
                            ID = 2,
                            InterestID = 1,
                            PersID = 1,
                            strLink = "www.nånting2.com"
                        },
                        new
                        {
                            ID = 3,
                            InterestID = 2,
                            PersID = 2,
                            strLink = "www.nånting3.com"
                        },
                        new
                        {
                            ID = 4,
                            InterestID = 3,
                            PersID = 3,
                            strLink = "www.nånting4.com"
                        });
                });

            modelBuilder.Entity("ADVLabb4.Models.Personer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Personers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Anas@qlok.com",
                            Name = "Anas",
                            Phone = 7055555
                        },
                        new
                        {
                            Id = 2,
                            Email = "Tobias@qlok.com",
                            Name = "Tobias",
                            Phone = 7066666
                        },
                        new
                        {
                            Id = 3,
                            Email = "Riedar@qlok.com",
                            Name = "Riedar",
                            Phone = 7077777
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
